# Generated by Django 3.0.8 on 2020-08-07 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_auto_20200807_1826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledetail',
            options={'verbose_name': 'SaleDetail', 'verbose_name_plural': 'SalesDetails'},
        ),
    ]
