# Generated by Django 3.0.8 on 2020-08-08 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_auto_20200807_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
