# Generated by Django 3.0.8 on 2020-08-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20200807_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=11),
        ),
    ]
