# Generated by Django 3.0.8 on 2020-08-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20200807_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saledetail',
            name='discount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=11),
        ),
    ]
