# Generated by Django 3.0.8 on 2020-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_auto_20200712_0711'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.CharField(default=None, max_length=45),
        ),
        migrations.AddField(
            model_name='item',
            name='gramsOrMilliliters',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=4),
        ),
        migrations.AddField(
            model_name='item',
            name='packaging',
            field=models.CharField(default=None, max_length=45),
        ),
    ]
