# Generated by Django 3.0.8 on 2020-07-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_auto_20200713_0401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
