# Generated by Django 3.0.8 on 2020-07-13 09:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0005_auto_20200713_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entrydetail',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
