# Generated by Django 3.0.8 on 2020-08-07 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saledetail',
            options={'verbose_name': 'SaleDetail', 'verbose_name_plural': 'SalesDetail'},
        ),
        migrations.AddField(
            model_name='sale',
            name='total_sale',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
